- name: Create /etc/puppet/hieradata
  file:
    path: /etc/puppet/hieradata
    state: directory
    mode: 0700

- name: Write hiera config
  when: (hieradata_files | length) > 0
  copy:
    mode: 0600
    dest:  /etc/puppet/hiera.yaml
    # TODO(emilien) Switch to Hiera5 format once we stop calling Hiera CLI
    # which is deprecated and should be replaced by "puppet lookup" command.
    content: |
      ---
      :backends:
        - json
      :json:
        :datadir: /etc/puppet/hieradata
      :hierarchy:
      {{ hieradata_files | to_nice_yaml if hieradata_files | type_debug == 'list' else hieradata_files }}
