- hosts: overcloud
  tasks:
    - name: test tripleo-hieradata
      include_role:
        name: tripleo-hieradata
      vars:
        hieradata_template: hieradata.j2.yaml
        # jinja2 escape trick for simple {{ and }} strings:
        variable_start_string: "{{ '{{' }}"
        variable_end_string: "{{ '}}' }}"
        hieradata_files:
          - node
          - common
