---
  - name: set file if already set by heat variable (backwards-compatibility)
    set_fact:
      image_filename: "{{ amp_image_filename }}"
    when: amp_image_filename is defined and not amp_image_filename == ''

  - name: set location if CentOS
    set_fact:
      image_filename: "/usr/share/openstack-octavia-amphora-images/amphora-x64-haproxy.qcow2"
    when: ansible_distribution == 'CentOS' and not image_filename is defined

  - name: set location if Red Hat
    set_fact:
      image_filename: "/usr/share/rhosp-director-images/octavia-amphora.qcow2"
    when: ansible_distribution == 'RedHat' and not image_filename is defined

  - name: check if amphora image file exists
    stat:
      path: "{{ image_filename }}"
      follow: true
      get_md5: true
    register: image_file_result

  - include_tasks: image_mgmt.yml
    when: image_file_result.stat.exists

  - name: check if pub key file exists
    stat: path="{{ amp_ssh_key_path }}"
    register: ssh_pub_key_file_result

  - name: upload pub key to overcloud
    shell: |
      openstack keypair show {{ amp_ssh_key_name }} || \
        openstack keypair create --public-key {{ amp_ssh_key_path }} {{ amp_ssh_key_name }}
    environment:
      OS_USERNAME: {{ auth_username }}
      OS_PASSWORD: {{ auth_password }}
      OS_PROJECT_NAME: {{ auth_project_name }}
    when: ssh_pub_key_file_result.stat.exists == True
